### ISSUE TITLE
Dynaconf[ini] should be installed by default

### ISSUE THREAD

**Issue by kairoaraujo** [vmware/repository-service-tuf-cli#119]
### Is your feature request related to a problem? Please describe.

The installation of repository-service-tuf doesn't install the `dynaconf[ini]`as a requirement, and the error is not explicit.

The error is during the logging only.

```shell
022-10-26T14:30:49.5665017Z ╔══════════════════════════════════════════════════════════════════════════════╗
2022-10-26T14:30:49.5666035Z ║                     Login to Repository Service for TUF                      ║
2022-10-26T14:30:49.5667693Z ╚══════════════════════════════════════════════════════════════════════════════╝
2022-10-26T14:30:49.5668058Z 
2022-10-26T14:30:49.5668439Z         The server and token will generate a token and it will be               
2022-10-26T14:30:49.5669068Z         stored in rstuf.ini                                                     
2022-10-26T14:30:49.8643130Z Traceback (most recent call last):
2022-10-26T14:30:49.8650051Z   File "/opt/hostedtoolcache/Python/3.10.8/x64/bin/rstuf", line 8, in <module>
2022-10-26T14:30:49.8650875Z     sys.exit(rstuf())
2022-10-26T14:30:49.8652180Z   File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
2022-10-26T14:30:49.8652581Z     return self.main(*args, **kwargs)
2022-10-26T14:30:49.8653135Z   File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/rich_click/rich_group.py", line 21, in main
2022-10-26T14:30:49.8653816Z     rv = super().main(*args, standalone_mode=False, **kwargs)
2022-10-26T14:30:49.8654377Z   File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/click/core.py", line 1055, in main
2022-10-26T14:30:49.8654694Z     rv = self.invoke(ctx)
2022-10-26T14:30:49.8655203Z   File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
2022-10-26T14:30:49.8656591Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2022-10-26T14:30:49.8657164Z   File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
2022-10-26T14:30:49.8663142Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2022-10-26T14:30:49.8663949Z   File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
2022-10-26T14:30:49.8668346Z     return ctx.invoke(self.callback, **ctx.params)
2022-10-26T14:30:49.8668996Z   File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/click/core.py", line 760, in invoke
2022-10-26T14:30:49.8672383Z     return __callback(*args, **kwargs)
2022-10-26T14:30:49.8673227Z   File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
2022-10-26T14:30:49.8673833Z     return f(get_current_context(), *args, **kwargs)
2022-10-26T14:30:49.8674533Z   File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/repository_service_tuf/cli/admin/login.py", line 139, in login
2022-10-26T14:30:49.8677144Z     _run_login(context, server_, user_, password_, expires_)
2022-10-26T14:30:49.8677794Z   File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/repository_service_tuf/cli/admin/login.py", line 100, in _run_login
2022-10-26T14:30:49.8679970Z     loaders.write(context.obj.get("config"), settings.to_dict())
2022-10-26T14:30:49.8680835Z   File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/dynaconf/loaders/__init__.py", line 277, in write
2022-10-26T14:30:49.8682725Z     loader.write(filename, data, merge=False)
2022-10-26T14:30:49.8683517Z   File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/dynaconf/loaders/ini_loader.py", line 60, in write
2022-10-26T14:30:49.8684078Z     new = ConfigObj()
2022-10-26T14:30:49.8686253Z TypeError: 'NoneType' object is not callable
```
https://github.com/vmware/repository-service-tuf/actions/runs/3329900645/jobs/5507703079

### Describe the solution you'd like

When `repository-service-tuf` is installed, the `dynaconf[ini]` is automatically downloaded and installed.

**Comment by kairoaraujo** [comment]
This bug is still valid, I checked with @MVrachev, and he will make a PR.
The `pyproject.toml` requires `dynaconf[ini]`.
